FROM python:3.8

 
# Creating Application Source Code Directory
RUN mkdir /chatbot
# Setting Home Directory for containers
WORKDIR /chatbot
# Copying src code to Container
COPY . /chatbot/lovcal-internet-search.py
# Application Environment variables
# Exposing Ports
EXPOSE 8501
